version: 2

models:
  - name: customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: order_payment_method_amounts
    columns:
      - name: order_id
        tests:
          - unique
          - not_null